[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "staywise-database"
version = "0.1.0"
dependencies = [
    "sqlalchemy>=2.0.0",
    "asyncpg",
    "pgvector",
    "pydantic-settings"
]

[tool.setuptools.packages.find]
include = ["database*"]
